import type { CourrierDef } from "../types";

/**
 * LA LIASSE DE LA TABLE D'AUGUSTIN — bistrot de quartier.
 *
 * La restauration reçoit peu de bonnes nouvelles par écrit et beaucoup de
 * contrôles : protection des populations, grossiste qui révise ses prix,
 * plateforme de livraison qui augmente sa commission, banque qui classe le
 * métier en risque élevé. Les courriers favorables viennent d'un guide, d'un
 * client ou de la mairie.
 */
export const BISTROT_COURRIERS: CourrierDef[] = [
  {
    code: "bistrot_avis_viral",
    expediteur: "Note interne · Réservations",
    objet: "Affluence à la suite du passage de votre dessert sur les réseaux",
    corps:
      "La photographie de notre dessert signature a dépassé deux cent mille vues. Le téléphone ne s'arrête plus depuis hier soir et le carnet du soir est complet jusqu'à la fin de la semaine.",
    signataire: "La responsable de salle",
    effet: "Demande du soir +30 % ce tour",
    enJeu: "Refuser du monde faute de places ou de brigade, c'est transformer un succès en clients perdus.",
    nature: "market",
    pli: "interne",
    emoji: "📸",
    scope: "market",
  },
  {
    code: "bistrot_inspection",
    expediteur: "Direction départementale de la protection des populations",
    objet: "Rapport de contrôle sanitaire et mesures à mettre en œuvre",
    corps:
      "Le contrôle inopiné du jeudi a relevé des manquements sur la traçabilité et la chaîne du froid. Les mises aux normes listées en annexe sont exigibles sans délai. Une contre-visite interviendra sans préavis.",
    signataire: "L'inspectrice de la sécurité sanitaire",
    effet: "Capacité de service −18 % ce tour (une table tirée au sort)",
    enJeu: "L'hygiène n'est pas une charge optionnelle : ce qu'on économise dessus se paie en fermeture.",
    nature: "internal",
    pli: "recommande",
    emoji: "🧾",
    scope: "team",
  },
  {
    code: "bistrot_panne_froid",
    expediteur: "Froid Marchal · Service d'urgence",
    objet: "Intervention sur votre chambre froide positive",
    corps:
      "Le groupe s'est arrêté dans la nuit de vendredi et la température est remontée durant tout le week-end. L'intégralité des denrées stockées est à détruire. Le procès-verbal de destruction est joint pour votre assureur.",
    signataire: "Le technicien frigoriste",
    effet: "Capacité −15 % et coût matières +14 % ce tour (une table tirée au sort)",
    enJeu: "En restauration, la marchandise perdue est payée deux fois : à l'achat, puis en service annulé.",
    nature: "internal",
    pli: "simple",
    emoji: "❄️",
    scope: "team",
  },
  {
    code: "bistrot_bureaux_vides",
    expediteur: "Association des commerçants du quartier d'affaires",
    objet: "Passage au télétravail de deux entreprises du quartier",
    corps:
      "Les deux plus gros employeurs de la rue passent à quatre jours de télétravail par semaine. Nos relevés annoncent une chute immédiate de la fréquentation du midi pour l'ensemble des établissements.",
    signataire: "Le président de l'association",
    effet: "Demande des déjeuners d'affaires −25 % ce tour",
    enJeu: "Le midi paie le loyer, le soir fait la marge : perdre un service, c'est perdre l'équilibre du modèle.",
    nature: "market",
    pli: "simple",
    emoji: "🏢",
    scope: "market",
  },
  {
    code: "bistrot_commission_livraison",
    expediteur: "Plateforme Livrapide · Direction des partenariats",
    objet: "Nouvelle grille de commission applicable aux restaurants partenaires",
    corps:
      "La commission prélevée sur chaque commande livrée passe à trente pour cent. Le maintien de votre présence sur l'application vaut acceptation de la nouvelle grille ; un retrait entraînerait la perte du volume associé.",
    signataire: "Le responsable des partenariats",
    effet: "Coût variable par couvert +10 % pendant 2 tours",
    enJeu: "Un canal qui apporte du volume mais dévore la marge : le chiffre d'affaires n'est pas le résultat.",
    nature: "macro",
    pli: "simple",
    emoji: "🛵",
    scope: "market",
  },
  {
    code: "bistrot_matieres_premieres",
    expediteur: "Grossiste Vandamme · Direction commerciale",
    objet: "Révision de nos tarifs — beurre, crème et viande",
    corps:
      "La collecte laitière et les cours de la viande nous imposent une révision de vingt-quatre pour cent sur ces familles, qui représentent la moitié de vos commandes habituelles. Le nouveau barème court sur deux trimestres.",
    signataire: "Le directeur commercial",
    effet: "Coût matières +24 % pendant 2 tours",
    enJeu:
      "Le ratio matières dérape : augmenter le ticket, réduire les portions ou changer la carte : il faut choisir.",
    nature: "macro",
    pli: "simple",
    emoji: "🥩",
    scope: "market",
  },
  {
    code: "bistrot_terrasse",
    expediteur: "Mairie · Service des occupations du domaine public",
    objet: "Extension exceptionnelle de votre terrasse",
    corps:
      "Compte tenu de la période de beau temps annoncée, nous autorisons l'extension de votre terrasse sur trois places de stationnement pour trois semaines. L'autorisation est gratuite et non reconductible de droit.",
    signataire: "Le chef de service",
    effet: "Demande globale +15 % ce tour",
    enJeu: "Les places en plus ne servent à rien sans la brigade pour les servir : la capacité est double.",
    nature: "market",
    pli: "simple",
    emoji: "🌞",
    scope: "market",
  },
  {
    code: "bistrot_credit_resserre",
    expediteur: "Crédit du Commerce · Direction des risques",
    objet: "Révision de votre autorisation de découvert",
    corps:
      "Notre comité classe la restauration traditionnelle en risque élevé. Votre autorisation est réduite et le taux applicable relevé pour les deux prochains trimestres. Un réexamen sera possible sur présentation de vos comptes annuels.",
    signataire: "Le directeur des risques",
    effet: "Taux d'intérêt ×1,5 pendant 2 tours",
    enJeu: "Un métier à faible marge supporte mal le coût du découvert : la trésorerie se pilote au jour le jour.",
    nature: "macro",
    pli: "recommande",
    emoji: "🏦",
    scope: "market",
  },
  {
    code: "bistrot_degat_des_eaux",
    expediteur: "Assurances du Littoral · Service sinistres",
    objet: "Déclaration de sinistre — inondation de votre cuisine",
    corps:
      "La canalisation située sous le passe a cédé. L'expert relève une cuisine inondée et une salle inexploitable le temps du séchage. La perte d'exploitation n'est indemnisée que si la garantie correspondante a été souscrite.",
    signataire: "Le gestionnaire de sinistres",
    effet: "Capacité −35 % et coût matières +10 % ce tour (une table ciblée)",
    enJeu: "La perte d'exploitation est l'essentiel du dommage : c'est elle que couvre la formule étendue.",
    nature: "internal",
    pli: "simple",
    emoji: "💧",
    scope: "team",
  },
  {
    code: "bistrot_fermeture_administrative",
    expediteur: "Préfecture · Bureau de la police administrative",
    objet: "Arrêté de fermeture administrative — quinze jours",
    corps:
      "À la suite du rapport de contrôle, la fermeture de votre établissement est prononcée pour quinze jours à compter de la notification. L'arrêté doit être affiché sur votre devanture pendant toute la durée de la mesure.",
    signataire: "Le chef de bureau",
    effet: "Capacité −45 % ce tour (une table ciblée)",
    enJeu: "Les salaires et le loyer continuent de courir : c'est la définition même d'une charge de structure.",
    nature: "internal",
    pli: "recommande",
    emoji: "🚷",
    scope: "team",
  },
  {
    code: "bistrot_guide_gastronomique",
    expediteur: "Guide gastronomique régional · Rédaction",
    objet: "Votre table dans notre prochaine édition",
    corps:
      "Notre inspecteur est passé deux fois, sans se faire connaître. Votre maison figurera dans l'édition à paraître, avec le mot « générosité ». Les établissements cités voient leur carnet se remplir sur six semaines.",
    signataire: "Le rédacteur en chef",
    effet: "Capacité commerciale +8 % pendant 2 tours (une table ciblée)",
    enJeu:
      "Le budget qualité paie avec retard, mais il paie : la réputation est un investissement à rendement différé.",
    nature: "market",
    pli: "simple",
    emoji: "📕",
    scope: "team",
  },
  {
    code: "bistrot_banque_conciliante",
    expediteur: "Crédit du Commerce · Agence de quartier",
    objet: "Allongement de votre crédit d'équipement",
    corps:
      "Vos ratios de gestion, et notamment la maîtrise de votre ratio matières, nous conduisent à allonger la durée de votre crédit d'équipement et à desserrer votre découvert. Les nouvelles conditions sont jointes.",
    signataire: "Votre chargée d'affaires",
    effet: "Taux d'intérêt ×0,7 pendant 2 tours (une table ciblée)",
    enJeu: "Un ratio matières maîtrisé se lit dans les comptes : c'est ce que regarde d'abord un banquier.",
    nature: "macro",
    pli: "simple",
    emoji: "🤝",
    scope: "team",
  },
  {
    code: "bistrot_banquet_surprise",
    expediteur: "Famille Delporte · Repas de mariage",
    objet: "Demande urgente — repas de 220 couverts dans trois jours",
    corps:
      "Le traiteur retenu pour notre réception vient de déposer le bilan et ne livrera pas. Nous cherchons une table capable d'assurer deux cent vingt couverts samedi. Nous réglons comptant le jour même.",
    signataire: "Pour la famille, M. Delporte",
    effet:
      "+220 couverts (échelle trimestre) servis d'office ce tour, réglés comptant, dans la limite de ce que vous pouvez produire",
    enJeu: "Dire oui suppose des denrées, une brigade et de la place : trois contraintes, une seule opportunité.",
    nature: "market",
    pli: "simple",
    emoji: "🥂",
    scope: "team",
  },
  {
    code: "bistrot_festival_ville",
    expediteur: "Mairie · Direction de l'animation",
    objet: "Programme de la fête de la ville — votre rue sur le parcours",
    corps:
      "Les festivités se tiendront sur trois jours et le parcours principal empruntera votre rue. Les éditions passées ont amené une affluence continue du midi à la fermeture, avec un pic le samedi soir.",
    signataire: "La directrice de l'animation",
    effet: "Demande globale +25 % ce tour",
    enJeu:
      "Sur-préparer coûte le prix des denrées jetées, sous-préparer coûte les clients refusés. Où placer le curseur ?",
    nature: "market",
    pli: "simple",
    emoji: "🎉",
    scope: "market",
  },
  {
    code: "bistrot_major_breakdown",
    expediteur: "Cuisines Professionnelles Lheureux · Service après-vente",
    objet: "Rapport d'intervention — four principal hors service",
    corps:
      "La sole et la résistance principale sont hors d'usage. La pièce n'est plus référencée : le remplacement de l'appareil s'impose, avec un délai de deux trimestres. La moitié de votre carte est concernée.",
    signataire: "Le responsable après-vente",
    effet: "Disponibilité −30 % pendant 2 tours (une entreprise tirée au sort)",
    enJeu: "Risque opérationnel & maintenance préventive",
    nature: "internal",
    pli: "simple",
    emoji: "🛑",
    scope: "team",
  },
  {
    code: "bistrot_tech_obsolescence",
    expediteur: "Cuisines Professionnelles Lheureux · Diagnostic énergétique",
    objet: "Diagnostic de votre matériel de cuisson",
    corps:
      "Vos plaques et votre four accusent quinze ans de service. Leur rendement thermique a chuté d'un tiers : les temps de cuisson s'allongent et votre facture d'énergie progresse à volume constant.",
    signataire: "Le technicien conseil",
    effet: "Disponibilité −10 % et coût matières +8 % pendant 2 tours (une entreprise tirée au sort)",
    enJeu: "Cycle de vie des actifs & veille technologique",
    nature: "internal",
    pli: "simple",
    emoji: "⏳",
    scope: "team",
  },
  {
    code: "bistrot_used_equipment_deal",
    expediteur: "Étude Marchand · Commissaire-priseur judiciaire",
    objet: "Vente du matériel d'une table étoilée cessant son activité",
    corps:
      "Piano de cuisson, cellule de refroidissement et batterie inox, entretenus et de moins de quatre ans, sont proposés en lot unique. La mise à prix est très inférieure au neuf ; l'enlèvement est à votre charge.",
    signataire: "Le commissaire-priseur",
    effet: "Disponibilité +12 % ce tour (équipe ciblée)",
    enJeu: "Décision d'investissement & coût d'opportunité",
    nature: "internal",
    pli: "simple",
    emoji: "🏭",
    scope: "team",
  },
  {
    code: "bistrot_food_truck",
    expediteur: "Mairie · Service des occupations du domaine public",
    objet: "Autorisation d'un commerce ambulant sur la place",
    corps:
      "Une activité de restauration rapide ambulante est autorisée sur la place les midis de semaine, à cinquante mètres de votre terrasse. L'autorisation est délivrée pour un an, renouvelable.",
    signataire: "Le chef de service",
    effet: "Demande des déjeuners d'affaires −18 % pendant 2 tours",
    enJeu: "La formule du midi vend du temps autant que de la cuisine : c'est là que le concurrent frappe.",
    nature: "competition",
    pli: "simple",
    emoji: "🚚",
    scope: "market",
  },
  {
    code: "bistrot_concurrent_etoile",
    expediteur: "Guide gastronomique régional · Rédaction",
    objet: "Distinction attribuée à un établissement de votre rue",
    corps:
      "Nous informons les professionnels du quartier que la table du 14 reçoit une étoile dans notre édition à paraître. L'affluence se reportera sur elle pendant plusieurs semaines, y compris de la part des habitués du voisinage.",
    signataire: "Le rédacteur en chef",
    effet: "Demande de la clientèle locale du soir −15 % pendant 2 tours",
    enJeu:
      "On ne se bat pas sur le terrain d'un concurrent mieux armé : la fidélité se construit sur ce qu'il n'offre pas.",
    nature: "competition",
    pli: "simple",
    emoji: "⭐",
    scope: "market",
  },
  {
    code: "bistrot_marche_hebdo",
    expediteur: "Mairie · Direction du commerce",
    objet: "Transfert du marché hebdomadaire sur votre rue",
    corps:
      "À compter de samedi, les quatre-vingts étals du marché seront installés sur votre section de rue. Le comptage de la dernière édition fait état de six mille passages entre huit heures et treize heures.",
    signataire: "L'adjointe au commerce",
    effet: "Demande globale +12 % pendant 2 tours",
    enJeu: "Le passage est une ressource gratuite : ce qu'on en tire dépend de la capacité à servir vite.",
    nature: "market",
    pli: "simple",
    emoji: "🧺",
    scope: "market",
  },
  {
    code: "bistrot_chef_absent",
    expediteur: "Caisse d'assurance maladie · Service des indemnités",
    objet: "Arrêt de travail de votre chef de cuisine",
    corps:
      "L'arrêt prescrit court sur six semaines pour fracture. Les indemnités journalières vous seront versées selon les modalités habituelles. Aucune reprise anticipée ne peut être envisagée sans avis médical.",
    signataire: "Le service des indemnités journalières",
    effet: "Couverts servis −20 % ce tour",
    enJeu:
      "Une entreprise qui tient sur une personne a une capacité fragile : le remplacement se prépare avant l'accident.",
    nature: "internal",
    pli: "simple",
    emoji: "🩼",
    scope: "team",
  },
  {
    code: "bistrot_critique_elogieuse",
    expediteur: "Chronique Les Tables de la ville",
    objet: "Publication de notre chronique sur votre maison",
    corps:
      "Notre article paraîtra demain matin. Il retient votre blanquette et le rapport qualité-prix de votre formule du soir. Notre audience est locale, fidèle, et réserve dans la semaine qui suit la parution.",
    signataire: "Le chroniqueur",
    effet: "Demande de votre bistrot +10 % pendant 2 tours",
    enJeu:
      "La réputation se gagne assiette par assiette et se perd en un service : la qualité est un investissement.",
    nature: "market",
    pli: "simple",
    emoji: "📝",
    scope: "team",
  },
];
