import type { CourrierDef } from "../types";

/**
 * LA LIASSE DE MAILLE & CO — boutique de maille en rue commerçante.
 *
 * Le courrier d'un commerce de détail vient d'un voisinage : la mairie,
 * l'association des commerçants, le syndic, le façonnier, l'assureur,
 * l'expert-comptable. Presque tous les expéditeurs sont à moins d'un
 * kilomètre, et c'est ce qui donne à ce secteur son échelle.
 */
export const BOUTIQUE_COURRIERS: CourrierDef[] = [
  {
    code: "boutique_travaux_voirie",
    expediteur: "Mairie · Direction de la voirie",
    objet: "Réfection de la chaussée — arrêté de circulation",
    corps:
      "Les travaux de réfection débuteront lundi pour une durée de dix-huit mois. Les barrières de chantier seront installées au droit de votre vitrine et le stationnement supprimé sur toute la section.",
    signataire: "L'adjoint aux travaux",
    effet: "Demande globale −18 % pendant 2 tours",
    enJeu:
      "Vos charges de structure, elles, ne baissent pas d'un centime : combien d'articles faut-il désormais vendre pour tenir ?",
    nature: "market",
    pli: "recommande",
    emoji: "🚧",
    scope: "market",
  },
  {
    code: "boutique_influenceur",
    expediteur: "Agence Trame · Relations d'influence",
    objet: "Retombées de la visite d'une créatrice dans votre boutique",
    corps:
      "La vidéo tournée dans vos cabines a dépassé le million de vues avant le dîner. Nous enregistrons une hausse considérable des recherches sur votre enseigne. L'affluence sera immédiate et ne durera pas.",
    signataire: "Votre chargée de compte",
    effet: "Demande des passants +30 % ce tour, sur toutes les références",
    enJeu:
      "Un pic ne profite qu'à celles qui ont du stock en réserve : l'anticipation vaut mieux que la chance.",
    nature: "market",
    pli: "simple",
    emoji: "📱",
    scope: "market",
  },
  {
    code: "boutique_demarque",
    expediteur: "Cabinet Delvaux · Expertise comptable",
    objet: "Observations sur votre inventaire de fin de période",
    corps:
      "Le rapprochement entre vos entrées et vos sorties fait apparaître un écart de deux cents pièces, des bonnets pour l'essentiel. Vol à l'étalage et erreurs de caisse se partagent probablement cette démarque. Elle est intégrée au coût de vos ventes.",
    signataire: "Votre expert-comptable",
    effet: "Coût d'achat effectif +9 % ce tour (une enseigne tirée au sort)",
    enJeu:
      "La marchandise perdue est payée mais jamais vendue : elle s'ajoute au coût de ce que vous vendez.",
    nature: "internal",
    pli: "simple",
    emoji: "🔍",
    scope: "team",
  },
  {
    code: "boutique_rupture_appro",
    expediteur: "Transitaire Vermeulen · Service clients",
    objet: "Immobilisation de votre conteneur au port",
    corps:
      "Votre conteneur est retenu au terminal dans l'attente d'un contrôle documentaire. Les trois quarts de votre réassort ne seront pas livrés avant six semaines. Nous ne sommes pas en mesure d'accélérer la procédure.",
    signataire: "Le responsable d'exploitation",
    effet: "Capacité de traitement −16 % ce tour (une enseigne tirée au sort)",
    enJeu: "Le rayon vide ne se rattrape pas : la vente manquée d'aujourd'hui ne revient pas demain.",
    nature: "internal",
    pli: "recommande",
    emoji: "📦",
    scope: "team",
  },
  {
    code: "boutique_ecommerce",
    expediteur: "Association des commerçants du centre-ville",
    objet: "Arrivée d'une plateforme de livraison rapide sur la commune",
    corps:
      "Une plateforme annonce la livraison en deux heures sur l'ensemble de la ville. Nos relevés de fréquentation montrent déjà un recul du flux en semaine dans toute la rue. Une réunion d'information se tiendra jeudi.",
    signataire: "La présidente de l'association",
    effet: "Demande globale −10 % pendant 2 tours",
    enJeu:
      "Quand le marché se contracte, on baisse les prix ou on soigne ce que le web ne sait pas vendre. Les deux coûtent.",
    nature: "competition",
    pli: "simple",
    emoji: "💻",
    scope: "market",
  },
  {
    code: "boutique_coton",
    expediteur: "Atelier Lemaire · Façonnier maille",
    objet: "Nouveau barème pour la prochaine collection",
    corps:
      "La laine mérinos et le coton ont fortement progressé, le fret également. Nous ne pouvons plus tenir nos prix et vous transmettons le barème applicable à votre prochaine collection, valable deux trimestres.",
    signataire: "La gérante",
    effet: "Coût d'achat +18 % pendant 2 tours",
    enJeu:
      "Le coefficient multiplicateur se comprime : répercuter sur le prix de vente, ou accepter de vendre moins cher que prévu ?",
    nature: "macro",
    pli: "recommande",
    emoji: "🧵",
    scope: "market",
  },
  {
    code: "boutique_credit_resserre",
    expediteur: "Crédit du Commerce · Agence de quartier",
    objet: "Modification des conditions applicables au petit commerce",
    corps:
      "Nos conditions de financement sont revues pour l'ensemble des commerces de détail de la place. Le taux de votre autorisation de découvert est majoré pour les deux prochains trimestres, sans modification du plafond accordé.",
    signataire: "Le directeur d'agence",
    effet: "Taux d'intérêt ×1,5 pendant 2 tours",
    enJeu: "Un découvert qui coûte cher transforme un problème de trésorerie en problème de résultat.",
    nature: "macro",
    pli: "recommande",
    emoji: "🏦",
    scope: "market",
  },
  {
    code: "boutique_pretexte_fete",
    expediteur: "Centrale de la maille · Note de tendance",
    objet: "Saison des cadeaux avancée de trois semaines",
    corps:
      "Les magazines féminins ont lancé la saison plus tôt que d'habitude. Nos adhérents constatent une arrivée précoce des clientes fidèles, liste en main, sur les pulls et les cardigans.",
    signataire: "Le service tendances",
    effet: "Demande des clientes fidèles +22 % ce tour (pulls et cardigans)",
    enJeu:
      "La fidélité se paie d'avance : les clientes qui reviennent sont celles qu'on a bien servies au tour précédent.",
    nature: "market",
    pli: "simple",
    emoji: "💐",
    scope: "market",
  },
  {
    code: "boutique_degat_des_eaux",
    expediteur: "Syndic Berthier · Gestion de copropriété",
    objet: "Déclaration de sinistre — dégât des eaux",
    corps:
      "Le chauffe-eau du logement situé au-dessus de votre local a fui durant la nuit. Le constat amiable est joint. La moitié de votre stock est déclarée impropre à la vente ; l'indemnisation dépendra de la garantie souscrite.",
    signataire: "Le gestionnaire d'immeuble",
    effet: "Capacité −30 % et coût d'achat +10 % ce tour (une enseigne ciblée)",
    enJeu: "C'est exactement le sinistre que couvre la multirisque commerce : la prime était-elle si chère ?",
    nature: "internal",
    pli: "recommande",
    emoji: "💧",
    scope: "team",
  },
  {
    code: "boutique_vitrine_primee",
    expediteur: "Association des commerçants du centre-ville",
    objet: "Attribution du prix de la plus belle vitrine",
    corps:
      "Le jury vous décerne son prix annuel à l'unanimité. La remise aura lieu samedi en présence de la presse locale, dont la photographie paraîtra en une du journal de la semaine.",
    signataire: "La présidente de l'association",
    effet: "Capacité de traitement +8 % ce tour (une enseigne ciblée)",
    enJeu: "Le soin apporté au point de vente est un investissement commercial : il se voit dans le flux client.",
    nature: "market",
    pli: "simple",
    emoji: "🏆",
    scope: "team",
  },
  {
    code: "boutique_banque_conciliante",
    expediteur: "Crédit du Commerce · Agence de quartier",
    objet: "Renégociation de votre autorisation de découvert",
    corps:
      "L'examen de vos derniers comptes nous conduit à revoir les conditions de votre découvert à la baisse, pour les deux prochains trimestres. Nous saluons la régularité de votre gestion sur les périodes écoulées.",
    signataire: "Le directeur d'agence",
    effet: "Taux d'intérêt ×0,7 pendant 2 tours (une enseigne ciblée)",
    enJeu: "La confiance bancaire se gagne sur des trimestres de gestion saine, pas sur une promesse.",
    nature: "macro",
    pli: "recommande",
    emoji: "🤝",
    scope: "team",
  },
  {
    code: "boutique_commande_ce",
    expediteur: "CSE des Papeteries de la Lys",
    objet: "Commande ferme — 500 pulls pour notre arbre de Noël",
    corps:
      "Notre comité souhaite offrir un pull à chacun de nos cinq cents salariés. Nous retenons votre col rond et confirmons la commande ce jour, réglée comptant à l'enlèvement, dans la limite de ce que vous pourrez fournir.",
    signataire: "Le secrétaire du comité",
    effet:
      "+500 pulls col rond (échelle trimestre) vendus d'office ce tour, réglés comptant, dans la limite du stock",
    enJeu:
      "L'opportunité ne se saisit qu'avec de la marchandise en réserve : le stock a un coût, et parfois une valeur.",
    nature: "market",
    pli: "recommande",
    emoji: "📋",
    scope: "team",
  },
  {
    code: "boutique_rue_pietonne",
    expediteur: "Mairie · Direction du commerce",
    objet: "Mise en service de la zone piétonne",
    corps:
      "Les travaux sont livrés : pavés neufs, jardinières et terrasses autorisées sur toute la rue. Nos comptages font état d'un flux du samedi multiplié par deux depuis la réouverture.",
    signataire: "L'adjointe au commerce",
    effet: "Demande globale +16 % pendant 2 tours",
    enJeu: "L'emplacement est le premier actif d'un commerce, et le seul qu'on ne trouve pas au bilan.",
    nature: "market",
    pli: "simple",
    emoji: "🌳",
    scope: "market",
  },
  {
    code: "boutique_major_breakdown",
    expediteur: "Bureau de contrôle Sécuritas Bâti",
    objet: "Rapport après effondrement d'un rayonnage",
    corps:
      "Le rayonnage central a cédé sous la charge. Nous constatons des marchandises abîmées et prononçons l'interdiction d'accès aux allées concernées jusqu'à remise en conformité, soit deux trimestres au vu des délais du fabricant.",
    signataire: "Le contrôleur technique",
    effet: "Disponibilité −30 % pendant 2 tours (une entreprise tirée au sort)",
    enJeu: "Risque opérationnel & maintenance du mobilier commercial",
    nature: "internal",
    pli: "recommande",
    emoji: "🛑",
    scope: "team",
  },
  {
    code: "boutique_tech_obsolescence",
    expediteur: "Éditeur CaissePro · Service abonnés",
    objet: "Fin de maintenance de votre logiciel de caisse",
    corps:
      "Votre version ne recevra plus de mise à jour à compter de ce trimestre. Les écarts d'inventaire et les erreurs de réassort constatés chez nos abonnés non migrés s'accentuent avec le temps. Une offre de migration est jointe.",
    signataire: "Le responsable du support",
    effet: "Disponibilité −10 % et coût matières +8 % pendant 2 tours (une entreprise tirée au sort)",
    enJeu: "Cycle de vie des actifs & veille technologique",
    nature: "internal",
    pli: "recommande",
    emoji: "⏳",
    scope: "team",
  },
  {
    code: "boutique_used_equipment_deal",
    expediteur: "Enseigne Bertin · Liquidation de mobilier",
    objet: "Cession de notre mobilier de magasin avant fermeture",
    corps:
      "Nous cessons notre activité et cédons présentoirs, portants et mannequins, tous en très bon état, à un quart de leur valeur. L'enlèvement est à votre charge et doit intervenir avant la fin du mois.",
    signataire: "Le gérant",
    effet: "Disponibilité +12 % ce tour (équipe ciblée)",
    enJeu: "Décision d'investissement & coût d'opportunité",
    nature: "internal",
    pli: "simple",
    emoji: "🏭",
    scope: "team",
  },
  {
    code: "boutique_fast_fashion",
    expediteur: "Association des commerçants du centre-ville",
    objet: "Ouverture d'une enseigne de fast fashion au 12 de la rue",
    corps:
      "L'ancien local du photographe accueillera une enseigne de mode à renouvellement hebdomadaire, sur quatre cents mètres carrés. Prix d'appel annoncés en vitrine dès l'ouverture. Le rythme de la rue va changer.",
    signataire: "La présidente de l'association",
    effet: "Demande globale −14 % pendant 2 tours",
    enJeu: "Face à un concurrent qui joue le volume, on ne gagne pas au prix : on gagne sur ce qu'il ne fait pas.",
    nature: "competition",
    pli: "simple",
    emoji: "🏬",
    scope: "market",
  },
  {
    code: "boutique_soldes_concurrent",
    expediteur: "Agence Trame · Veille commerciale",
    objet: "Ventes privées anticipées chez votre voisine",
    corps:
      "La boutique du 8 a lancé ses ventes privées deux semaines avant la date d'usage, avec affichage sur rue et envoi à son fichier clients. Les passants y entrent d'abord ; votre clientèle fidèle, elle, ne bouge pas.",
    signataire: "Votre chargée de compte",
    effet: "Demande des passants −20 % ce tour",
    enJeu:
      "Les clientes fidèles restent, les passants suivent l'affiche : votre chiffre dépend de la part de chacun.",
    nature: "competition",
    pli: "simple",
    emoji: "🏷️",
    scope: "market",
  },
  {
    code: "boutique_vendeuse_star",
    expediteur: "Note interne · Encadrement du magasin",
    objet: "Résultats de votre nouvelle vendeuse à l'issue de sa période d'essai",
    corps:
      "Elle connaît les clientes par leur prénom et son panier moyen dépasse de moitié celui de l'équipe, sans qu'aucun prix n'ait été baissé. Je propose la confirmation de son embauche.",
    signataire: "La responsable de magasin",
    effet: "Demande de votre boutique +8 % pendant 2 tours",
    enJeu: "La relation client est un actif qui ne figure à aucun bilan, et qui pèse sur le chiffre d'affaires.",
    nature: "internal",
    pli: "simple",
    emoji: "🌟",
    scope: "team",
  },
  {
    code: "boutique_greve_transporteur",
    expediteur: "Transporteur Delahaye · Direction",
    objet: "Mouvement social — suspension des livraisons",
    corps:
      "Un mouvement social touche notre plateforme depuis lundi. Vos colis en provenance du façonnier restent à quai et seront livrés avec une semaine de retard au minimum. Nous vous prions de nous en excuser.",
    signataire: "Le directeur d'exploitation",
    effet: "Mise en rayon −15 % ce tour",
    enJeu: "La rupture ne vient pas toujours de la demande : la chaîne d'approvisionnement a ses propres pannes.",
    nature: "internal",
    pli: "simple",
    emoji: "🚚",
    scope: "team",
  },
  {
    code: "boutique_marche_noel",
    expediteur: "Mairie · Direction du commerce",
    objet: "Implantation du marché de Noël devant votre boutique",
    corps:
      "Les chalets seront installés sur votre section de rue pour trois semaines. Les éditions précédentes ont amené dix mille passants supplémentaires chaque week-end. L'accès à votre vitrine reste dégagé.",
    signataire: "L'adjointe au commerce",
    effet: "Demande globale +20 % ce tour",
    enJeu: "Un pic de passage ne se sert qu'avec du stock : c'est au trimestre d'avant qu'il se prépare.",
    nature: "market",
    pli: "simple",
    emoji: "🎄",
    scope: "market",
  },
];
