import type { CourrierDef } from "../types";

/**
 * LA LIASSE DE PIXEL & CO — vente en ligne.
 *
 * Le pure player reçoit surtout des notifications de plateformes : régie
 * publicitaire, marketplace, transporteur, prestataire de paiement. Ce sont
 * des courriers qui ne se négocient pas — ils annoncent une décision déjà
 * prise ailleurs, et c'est précisément la leçon du secteur.
 */
export const ECOMMERCE_COURRIERS: CourrierDef[] = [
  {
    code: "ecom_algo_publicitaire",
    expediteur: "Régie publicitaire Audiences · Notification partenaire",
    objet: "Évolution de notre modèle d'enchères publicitaires",
    corps:
      "Notre système d'enchères évolue au profit des annonceurs à fort historique. Le coût par clic de vos campagnes est réévalué en conséquence, dès le prochain cycle de facturation. Aucune action n'est requise de votre part.",
    signataire: "L'équipe Partenaires",
    effet: "Demande des nouveaux clients −28 % pendant 2 tours",
    enJeu:
      "Votre trafic dépend d'un intermédiaire qui fixe ses règles seul : la base de clients fidèles est la seule qui vous appartienne.",
    nature: "macro",
    pli: "simple",
    emoji: "📉",
    scope: "market",
  },
  {
    code: "ecom_vague_retours",
    expediteur: "Note interne · Service après-vente",
    objet: "Taux de retour anormal sur le dernier lot reçu",
    corps:
      "Les teintes livrées ne correspondent pas aux visuels du site. Un client sur quatre renvoie son colis en invoquant la non-conformité, ce qui nous est opposable. Le double transport et la remise en stock sont à notre charge.",
    signataire: "La responsable du service après-vente",
    effet: "Coût variable par commande +16 % ce tour (une enseigne tirée au sort)",
    enJeu:
      "Un retour coûte deux transports et une remise en stock, pour zéro chiffre d'affaires : c'est de la marge pure qui part.",
    nature: "internal",
    pli: "interne",
    emoji: "📦",
    scope: "team",
  },
  {
    code: "ecom_transporteur",
    expediteur: "Transporteur Delahaye · Direction d'exploitation",
    objet: "Mouvement social — blocage de nos dépôts",
    corps:
      "Nos plateformes sont bloquées depuis lundi et le resteront une semaine au moins. Vos colis déjà enlevés attendent sur nos quais. Nous ne prenons plus d'enlèvement jusqu'à nouvel ordre.",
    signataire: "Le directeur d'exploitation",
    effet: "Capacité d'expédition −20 % ce tour",
    enJeu: "Vous avez encaissé, mais vous n'avez pas livré : la promesse de délai fait partie du produit.",
    nature: "macro",
    pli: "simple",
    emoji: "🚚",
    scope: "market",
  },
  {
    code: "ecom_influenceur",
    expediteur: "Agence Trame · Relations d'influence",
    objet: "Retombées de la vidéo de déballage publiée hier",
    corps:
      "La vidéo a dépassé deux millions de vues en une nuit. Votre serveur a tenu, de justesse. L'affluence se maintiendra quelques jours : seule la disponibilité en stock limitera les ventes.",
    signataire: "Votre chargée de compte",
    effet: "Demande globale +26 % ce tour",
    enJeu: "Un pic gratuit ne profite qu'à ceux qui ont le stock ET la capacité de préparer : l'aubaine se prépare.",
    nature: "market",
    pli: "simple",
    emoji: "🎬",
    scope: "market",
  },
  {
    code: "ecom_marketplace_commission",
    expediteur: "Marketplace Vendora · Conditions vendeurs",
    objet: "Modification de la commission applicable aux vendeurs tiers",
    corps:
      "La commission passe de douze à dix-huit pour cent au prochain cycle. La poursuite de vos ventes sur la plateforme vaut acceptation. Le retrait de votre boutique reste possible, sans transfert de votre historique d'avis.",
    signataire: "L'équipe Vendeurs",
    effet: "Demande marketplace −18 % pendant 2 tours",
    enJeu: "Un canal qui apporte du volume mais dicte ses conditions : dépendre d'un seul intermédiaire a un prix.",
    nature: "competition",
    pli: "simple",
    emoji: "🏷️",
    scope: "market",
  },
  {
    code: "ecom_frais_port",
    expediteur: "Transporteur Delahaye · Direction commerciale",
    objet: "Nouvelle grille tarifaire et surcharges de saison",
    corps:
      "L'évolution du carburant et des taxes nous conduit à réviser l'ensemble de notre grille, surcharges de haute saison comprises. Le nouveau barème s'applique à tous vos envois pour les deux prochains trimestres.",
    signataire: "Le directeur commercial",
    effet: "Coût variable par commande +20 % pendant 2 tours",
    enJeu:
      "La marge par commande se comprime sans que le prix affiché bouge : offrir les frais de port n'est jamais gratuit.",
    nature: "macro",
    pli: "simple",
    emoji: "⛽",
    scope: "market",
  },
  {
    code: "ecom_credit_resserre",
    expediteur: "Banque des Professions · Direction des engagements",
    objet: "Révision de vos conditions — absence d'actif nantissable",
    corps:
      "Votre bilan ne présente ni immobilier ni équipement mobilisable en garantie ; votre stock constitue votre seul actif significatif. Les conditions de votre ligne de financement sont durcies pour deux trimestres.",
    signataire: "Le directeur des engagements",
    effet: "Taux d'intérêt ×1,5 pendant 2 tours",
    enJeu: "Un pure player finance son stock par le découvert : le coût de l'argent devient un coût d'exploitation.",
    nature: "macro",
    pli: "recommande",
    emoji: "🏦",
    scope: "market",
  },
  {
    code: "ecom_rupture_appro",
    expediteur: "Transitaire Vermeulen · Service clients",
    objet: "Immobilisation de votre conteneur — contrôle douanier",
    corps:
      "Après six semaines de mer, votre conteneur est retenu pour contrôle documentaire. Les trois références qui composent l'essentiel de vos ventes s'y trouvent. Nous ne pouvons pas nous engager sur une date de mise à disposition.",
    signataire: "Le responsable d'exploitation",
    effet: "Capacité d'expédition −18 % ce tour (une enseigne tirée au sort)",
    enJeu: "L'import direct coûte moins cher à l'achat et beaucoup plus cher en délai : le prix n'est pas le seul critère.",
    nature: "internal",
    pli: "simple",
    emoji: "🚢",
    scope: "team",
  },
  {
    code: "ecom_cyberattaque",
    expediteur: "Hébergeur Axone · Cellule de sécurité",
    objet: "Incident critique — boutique hors ligne et base clients chiffrée",
    corps:
      "Un rançongiciel a chiffré votre boutique et votre base clients. Le site est retiré du réseau le temps de l'assainissement. Chaque heure d'indisponibilité se traduit par des commandes passées ailleurs.",
    signataire: "Le responsable de la sécurité",
    effet: "Capacité −38 % ce tour (une enseigne ciblée)",
    enJeu: "Quand la boutique EST le site, l'assurance cyber n'est pas une option de confort.",
    nature: "internal",
    pli: "simple",
    emoji: "🔒",
    scope: "team",
  },
  {
    code: "ecom_entrepot",
    expediteur: "Assurances du Littoral · Service sinistres",
    objet: "Déclaration de sinistre — infiltration en toiture de votre entrepôt",
    corps:
      "L'expert constate qu'un tiers de votre stock est impropre à la vente et que le reste présente des traces d'humidité. La garantie « marchandises stockées » s'applique selon les plafonds et franchises de votre contrat.",
    signataire: "La gestionnaire de sinistres",
    effet: "Capacité −30 % et coût variable +12 % ce tour (une enseigne ciblée)",
    enJeu: "Le stock d'un pure player est son actif principal : ce que couvre la formule étendue.",
    nature: "internal",
    pli: "simple",
    emoji: "💧",
    scope: "team",
  },
  {
    code: "ecom_presse",
    expediteur: "Magazine Intérieurs · Rédaction",
    objet: "Sélection de trois de vos produits dans notre numéro à paraître",
    corps:
      "Notre dossier de saison retient trois de vos références, en double page, avec l'adresse de votre site. Nos lecteurs viennent directement, sans passer par un moteur de recherche ni par une publicité.",
    signataire: "La rédactrice en chef",
    effet: "Capacité commerciale +7 % pendant 2 tours (une enseigne ciblée)",
    enJeu: "Un client qui vient sans publicité coûte zéro euro d'acquisition : c'est là que se trouve la vraie marge.",
    nature: "market",
    pli: "simple",
    emoji: "📰",
    scope: "team",
  },
  {
    code: "ecom_banque_conciliante",
    expediteur: "Banque des Professions · Agence entreprises",
    objet: "Financement de votre stock de fin d'année",
    corps:
      "Votre taux de retour maîtrisé et la récurrence de votre clientèle nous conduisent à accepter le financement de votre stock de saison, à des conditions préférentielles valables deux trimestres.",
    signataire: "Votre chargée d'affaires",
    effet: "Taux d'intérêt ×0,7 pendant 2 tours (une enseigne ciblée)",
    enJeu: "Une base de clients qui revient est une garantie : elle vaut mieux qu'un entrepôt à l'actif.",
    nature: "macro",
    pli: "simple",
    emoji: "🤝",
    scope: "team",
  },
  {
    code: "ecom_commande_b2b",
    expediteur: "Aménagements Carrel · Direction des achats",
    objet: "Commande unique — équipement de trois plateaux de bureaux",
    corps:
      "Nous équipons trois plateaux et vous passons une commande ferme de sept cents articles de votre catalogue. Nous réglons comptant à la livraison, dans la limite de ce que vous avez en stock.",
    signataire: "Le directeur des achats",
    effet:
      "+700 commandes (échelle trimestre) vendues d'office ce tour, réglées comptant, dans la limite du stock",
    enJeu: "Une commande B2B ne coûte rien en acquisition : la marge y est mécaniquement supérieure.",
    nature: "market",
    pli: "recommande",
    emoji: "📋",
    scope: "team",
  },
  {
    code: "ecom_black_friday",
    expediteur: "Fédération du commerce en ligne · Note aux adhérents",
    objet: "Préparation de l'opération commerciale de fin novembre",
    corps:
      "Les quatre jours de l'opération concentrent près d'un dixième du chiffre d'affaires annuel du secteur. Les principaux acteurs ont déjà lancé leurs campagnes de préchauffe. Les stocks doivent être en place la semaine précédente.",
    signataire: "Le délégué général",
    effet: "Demande globale +45 % ce tour",
    enJeu:
      "Tout le monde a la même hausse de demande : l'écart se fait sur le stock disponible et la capacité d'expédition.",
    nature: "market",
    pli: "simple",
    emoji: "🛒",
    scope: "market",
  },
  {
    code: "ecom_major_breakdown",
    expediteur: "Convoyeurs Lasalle · Service après-vente",
    objet: "Rapport d'intervention — blocage du convoyeur de tri",
    corps:
      "Le moteur d'entraînement principal est grillé et le châssis a subi des contraintes. La remise en cadence nominale demandera deux trimestres. La préparation manuelle reste possible, à un rythme très inférieur.",
    signataire: "Le responsable après-vente",
    effet: "Disponibilité −30 % pendant 2 tours (une entreprise tirée au sort)",
    enJeu: "Risque opérationnel & maintenance préventive",
    nature: "internal",
    pli: "simple",
    emoji: "🛑",
    scope: "team",
  },
  {
    code: "ecom_tech_obsolescence",
    expediteur: "Éditeur Stocklog · Service abonnés",
    objet: "Fin de maintenance de votre logiciel de gestion d'entrepôt",
    corps:
      "Votre version n'est plus maintenue et ne suit plus votre volume de commandes. Les erreurs de prélèvement et la surconsommation d'emballages constatées chez nos abonnés non migrés s'aggravent trimestre après trimestre.",
    signataire: "Le responsable du support",
    effet: "Disponibilité −10 % et coût matières +8 % pendant 2 tours (une entreprise tirée au sort)",
    enJeu: "Cycle de vie des actifs & veille technologique",
    nature: "internal",
    pli: "simple",
    emoji: "⏳",
    scope: "team",
  },
  {
    code: "ecom_used_equipment_deal",
    expediteur: "Administrateur judiciaire Brunet",
    objet: "Cession d'équipements logistiques — procédure de redressement",
    corps:
      "Dans le cadre du redressement d'un e-commerçant voisin, transpalettes électriques et convoyeur automatisé sont cédés en lot. Le matériel a trois ans et l'enlèvement doit intervenir sous dix jours.",
    signataire: "L'administrateur judiciaire",
    effet: "Disponibilité +12 % ce tour (équipe ciblée)",
    enJeu: "Décision d'investissement & coût d'opportunité",
    nature: "internal",
    pli: "simple",
    emoji: "🏭",
    scope: "team",
  },
  {
    code: "ecom_geant_promo",
    expediteur: "Régie publicitaire Audiences · Note de marché",
    objet: "Tension sur les enchères pendant les journées promotionnelles",
    corps:
      "Le principal acteur du secteur tient ses quarante-huit heures de remises massives. Sur cette période, le coût d'acquisition observé double à taux de conversion constant sur l'ensemble de nos annonceurs.",
    signataire: "L'équipe Partenaires",
    effet: "Demande des nouveaux clients −25 % ce tour",
    enJeu: "Un coût d'acquisition qui double le temps d'une promo concurrente : il vaut parfois mieux couper que suivre.",
    nature: "competition",
    pli: "simple",
    emoji: "🏷️",
    scope: "market",
  },
  {
    code: "ecom_livraison_gratuite",
    expediteur: "Fédération du commerce en ligne · Observatoire",
    objet: "Passage d'un concurrent à la livraison gratuite sans minimum",
    corps:
      "Un acteur de votre segment supprime toute condition de montant sur la livraison. Notre observatoire constate que le report concerne d'abord les petits paniers, les plus sensibles aux frais d'expédition.",
    signataire: "Le responsable de l'observatoire",
    effet: "Demande globale −10 % pendant 2 tours",
    enJeu: "La livraison gratuite n'est pas gratuite : quelqu'un la paie, et ce n'est pas toujours le client.",
    nature: "competition",
    pli: "simple",
    emoji: "📦",
    scope: "market",
  },
  {
    code: "ecom_avis_cinq_etoiles",
    expediteur: "Plateforme d'avis vérifiés · Rapport mensuel",
    objet: "Progression de votre note et de votre taux de recommandation",
    corps:
      "Votre note moyenne progresse de sept dixièmes en un mois, les commentaires citant très majoritairement votre service après-vente. Le taux de clients déclarant vous recommander atteint son plus haut niveau.",
    signataire: "Le service statistiques",
    effet: "Demande des clients récurrents de votre boutique +20 % pendant 2 tours",
    enJeu: "Un client fidèle coûte dix fois moins qu'un client acquis : la rétention est la publicité la moins chère.",
    nature: "market",
    pli: "simple",
    emoji: "⭐",
    scope: "team",
  },
  {
    code: "ecom_panne_paiement",
    expediteur: "Prestataire de paiement Monetis · Direction technique",
    objet: "Interruption de service sur notre passerelle de paiement",
    corps:
      "Notre passerelle est indisponible depuis ce matin et le rétablissement complet est annoncé sous trois jours. Aucune transaction par carte ne peut aboutir. Les paniers constitués sur votre site sont abandonnés au règlement.",
    signataire: "Le directeur technique",
    effet: "Commandes servies −30 % ce tour",
    enJeu:
      "Une boutique en ligne dépend de prestataires qu'elle ne contrôle pas : le risque opérationnel se contractualise.",
    nature: "internal",
    pli: "simple",
    emoji: "💳",
    scope: "team",
  },
  {
    code: "ecom_taxe_colis",
    expediteur: "Direction générale des douanes · Bureau des particuliers et du commerce",
    objet: "Entrée en vigueur des droits sur les colis importés",
    corps:
      "À compter du prochain trimestre, tout colis importé hors Union européenne supporte des droits et des frais de dédouanement, sans seuil d'exonération. Vos déclarations devront être déposées à chaque envoi.",
    signataire: "Le chef de bureau",
    effet: "Coût d'achat +8 % pendant 2 tours",
    enJeu:
      "Une taxe sur les achats est un coût variable : elle remonte le seuil, et la question est de la répercuter ou non.",
    nature: "macro",
    pli: "simple",
    emoji: "🛃",
    scope: "market",
  },
];
