import type { CourrierDef } from "../types";

/**
 * LA LIASSE DE VOLT FITNESS — salle de sport par abonnement.
 *
 * Un club vit d'un portefeuille d'adhérents : ses courriers parlent donc
 * d'entrées et de sorties — un contrat d'entreprise signé, une mutuelle qui
 * rembourse, un coach qui part avec ses élèves, un concurrent qui ouvre. Ce
 * sont des mouvements de portefeuille avant d'être des événements.
 */
export const FITNESS_COURRIERS: CourrierDef[] = [
  {
    code: "fitness_rentree_sportive",
    expediteur: "Note interne · Accueil du club",
    objet: "Affluence du premier lundi de janvier",
    corps:
      "La file d'attente déborde sur le parking depuis l'ouverture. Nous enregistrons trois fois plus de demandes d'inscription qu'un lundi ordinaire, presque toutes sur la formule d'essai.",
    signataire: "La responsable d'accueil",
    effet: "Demande du segment « résolutions » +35 % ce tour",
    enJeu:
      "Ces adhérents-là remplissent la salle et repartent au printemps : les inscrire coûte, les garder rapporte.",
    nature: "market",
    pli: "simple",
    emoji: "🎯",
    scope: "market",
  },
  {
    code: "fitness_low_cost",
    expediteur: "Syndicat des exploitants de salles de sport",
    objet: "Ouverture d'un club sans personnel à votre adresse voisine",
    corps:
      "Un opérateur à bas prix ouvre en face de votre club : dix-neuf euros quatre-vingt-dix par mois, accès continu, aucun encadrement sur place. Son affichage est visible depuis votre parking.",
    signataire: "Le secrétaire du syndicat",
    effet: "Demande globale −16 % pendant 2 tours",
    enJeu: "Face à un concurrent qui casse les prix, s'aligner détruit la marge : reste ce qu'il ne sait pas offrir.",
    nature: "competition",
    pli: "simple",
    emoji: "💸",
    scope: "market",
  },
  {
    code: "fitness_panne_parc",
    expediteur: "Cardio Équipements Rousseau · Service après-vente",
    objet: "Indisponibilité de pièces — six tapis et quatre vélos",
    corps:
      "Les cartes électroniques de ces séries sont en rupture chez le constructeur. Nos délais d'approvisionnement sont de trois semaines. Les appareils concernés doivent être condamnés et signalés d'ici là.",
    signataire: "Le responsable après-vente",
    effet: "Capacité d'accueil −20 % ce tour (une salle tirée au sort)",
    enJeu: "Une machine à l'arrêt se voit tout de suite, et se retrouve dans les avis, puis dans les résiliations.",
    nature: "internal",
    pli: "simple",
    emoji: "🔧",
    scope: "team",
  },
  {
    code: "fitness_coach_star",
    expediteur: "Note interne · Planning des cours collectifs",
    objet: "Saturation des créneaux d'un de nos éducateurs",
    corps:
      "Ses cours affichent complet trois semaines à l'avance et la liste d'attente s'allonge. Plusieurs adhérents déclarent avoir renouvelé leur abonnement pour ces créneaux précis.",
    signataire: "Le responsable du planning",
    effet: "Demande des pratiquants réguliers +30 % ce tour",
    enJeu:
      "Dans un modèle par abonnement, ce qui retient vaut plus que ce qui attire : un régulier paie tous les trimestres.",
    nature: "market",
    pli: "simple",
    emoji: "🏋️",
    scope: "market",
  },
  {
    code: "fitness_energie",
    expediteur: "Fournisseur d'énergie Caloris · Service entreprises",
    objet: "Régularisation et nouveau barème de votre contrat",
    corps:
      "Votre consommation trimestrielle — chauffage, eau chaude sanitaire, ventilation et alimentation des appareils — est facturée au nouveau barème, en hausse de vingt-huit pour cent. La régularisation figure sur la facture jointe.",
    signataire: "Le conseiller entreprises",
    effet: "Coût variable par adhérent +28 % pendant 2 tours",
    enJeu:
      "Une charge qui grimpe quand la salle est vide : l'été, elle tombe sans aucun abonnement pour la couvrir.",
    nature: "macro",
    pli: "recommande",
    emoji: "⚡",
    scope: "market",
  },
  {
    code: "fitness_teletravail",
    expediteur: "Groupe Mercier · Direction des ressources humaines",
    objet: "Non-renouvellement de notre convention de partenariat",
    corps:
      "Nos salariés étant passés en télétravail quatre jours sur cinq, la fréquentation de votre club par nos équipes est devenue marginale. Nous ne renouvellerons pas la convention à son échéance.",
    signataire: "La directrice des ressources humaines",
    effet: "Demande des contrats entreprises −22 % pendant 2 tours",
    enJeu:
      "Perdre un contrat corporate, c'est perdre d'un coup ce que trente inscriptions individuelles rapportent.",
    nature: "macro",
    pli: "recommande",
    emoji: "🏢",
    scope: "market",
  },
  {
    code: "fitness_credit_resserre",
    expediteur: "Banque des Professions · Direction des engagements",
    objet: "Renégociation de votre crédit d'équipement",
    corps:
      "Notre comité des risques classe l'exploitation de salles de sport parmi les activités volatiles. Le taux de votre crédit d'équipement est relevé pour les deux prochains trimestres, à échéancier inchangé.",
    signataire: "Le directeur des engagements",
    effet: "Taux d'intérêt ×1,5 pendant 2 tours",
    enJeu: "Un parc de machines financé à crédit se rembourse même les trimestres où la salle est vide.",
    nature: "macro",
    pli: "recommande",
    emoji: "🏦",
    scope: "market",
  },
  {
    code: "fitness_canicule",
    expediteur: "Préfecture · Cellule de veille sanitaire",
    objet: "Épisode caniculaire — recommandations aux établissements sportifs",
    corps:
      "Le département est placé en vigilance canicule pour la semaine. Il est recommandé de limiter la fréquentation aux heures les plus chaudes et d'interrompre les activités si la température intérieure dépasse trente degrés.",
    signataire: "Le directeur de cabinet",
    effet: "Capacité d'accueil −12 % ce tour",
    enJeu: "L'été cumule tout : moins d'adhérents, plus d'énergie, et des charges qui ne bougent pas.",
    nature: "market",
    pli: "simple",
    emoji: "🥵",
    scope: "market",
  },
  {
    code: "fitness_accident",
    expediteur: "Cabinet Lermite · Avocats, pour son client adhérent",
    objet: "Accident survenu sur votre plateau de musculation",
    corps:
      "Notre client a été blessé par une barre dont le réglage n'était pas conforme. Un arrêt de travail de six semaines lui a été prescrit. Nous vous invitons à déclarer le sinistre à votre assureur de responsabilité civile.",
    signataire: "Maître Lermite",
    effet: "Capacité −22 % et coût variable +14 % pendant 2 tours (une salle ciblée)",
    enJeu: "C'est exactement ce que couvre la responsabilité civile exploitant : la prime valait-elle son prix ?",
    nature: "internal",
    pli: "recommande",
    emoji: "⚠️",
    scope: "team",
  },
  {
    code: "fitness_degat_des_eaux",
    expediteur: "Assurances du Littoral · Service sinistres",
    objet: "Déclaration de sinistre — vestiaires et douches hors service",
    corps:
      "La rupture de la canalisation d'alimentation a inondé les vestiaires. L'expert prononce leur condamnation jusqu'à réfection complète. L'accès à la salle sans douche n'est pas envisageable en pratique.",
    signataire: "Le gestionnaire de sinistres",
    effet: "Capacité −34 % ce tour (une salle ciblée)",
    enJeu: "La perte d'exploitation dépasse largement le coût des travaux : c'est elle qu'il faut assurer.",
    nature: "internal",
    pli: "recommande",
    emoji: "💧",
    scope: "team",
  },
  {
    code: "fitness_reportage",
    expediteur: "Quotidien régional · Rédaction locale",
    objet: "Parution de notre reportage sur votre programme seniors",
    corps:
      "Notre page « initiatives » est consacrée à votre programme destiné aux plus de soixante ans, avec photographies et témoignages d'adhérents. La parution est prévue samedi, jour de plus forte diffusion.",
    signataire: "La cheffe d'édition",
    effet: "Capacité commerciale +8 % pendant 2 tours (une salle ciblée)",
    enJeu: "Ces adhérents-là arrivent sans budget d'acquisition, et ce sont souvent les plus fidèles.",
    nature: "market",
    pli: "simple",
    emoji: "📰",
    scope: "team",
  },
  {
    code: "fitness_banque_conciliante",
    expediteur: "Banque des Professions · Agence entreprises",
    objet: "Révision favorable de vos conditions de financement",
    corps:
      "Votre taux de rétention, supérieur à la moyenne du secteur, nous conduit à considérer vos abonnements comme un revenu prévisible. Les conditions de votre crédit sont revues à la baisse pour deux trimestres.",
    signataire: "Votre chargé d'affaires",
    effet: "Taux d'intérêt ×0,7 pendant 2 tours (une salle ciblée)",
    enJeu: "Un revenu récurrent est la meilleure garantie qui soit : il est prévisible, donc finançable.",
    nature: "macro",
    pli: "recommande",
    emoji: "🤝",
    scope: "team",
  },
  {
    code: "fitness_contrat_surprise",
    expediteur: "Fabrique Delorme · Direction des ressources humaines",
    objet: "Convention de partenariat pour nos 200 salariés",
    corps:
      "Nous souhaitons offrir à nos deux cents salariés un accès à votre club à compter de janvier, réglé en une fois pour le trimestre. Nous attendons votre confirmation de capacité d'accueil avant signature.",
    signataire: "Le directeur des ressources humaines",
    effet:
      "+200 adhérents (échelle trimestre) inscrits d'office ce tour, réglés comptant, dans la limite de vos places",
    enJeu: "Encore faut-il pouvoir les accueillir : sur-vendre sans encadrement fait fuir les adhérents en place.",
    nature: "market",
    pli: "recommande",
    emoji: "📋",
    scope: "team",
  },
  {
    code: "fitness_marathon",
    expediteur: "Comité d'organisation du marathon de la ville",
    objet: "Ouverture des inscriptions — douze mille coureurs attendus",
    corps:
      "Les inscriptions sont ouvertes pour l'édition de printemps, trois mois avant le départ. Les clubs partenaires constatent chaque année une hausse marquée des demandes de préparation sur cette période.",
    signataire: "Le président du comité",
    effet: "Demande globale +28 % ce tour",
    enJeu:
      "Un afflux ponctuel dans un modèle par abonnement : ce qui compte, c'est combien seront encore là en juin.",
    nature: "market",
    pli: "simple",
    emoji: "🏃",
    scope: "market",
  },
  {
    code: "fitness_major_breakdown",
    expediteur: "Bureau de contrôle Sécuritas Bâti",
    objet: "Rapport après court-circuit du tableau général",
    corps:
      "Le tableau général a subi un court-circuit et l'alimentation du plateau est coupée. Nous prononçons l'interdiction d'exploiter les appareils concernés jusqu'à remise en conformité, soit deux trimestres au vu des devis.",
    signataire: "Le contrôleur technique",
    effet: "Disponibilité −30 % pendant 2 tours (une entreprise tirée au sort)",
    enJeu: "Risque opérationnel & maintenance préventive",
    nature: "internal",
    pli: "recommande",
    emoji: "🛑",
    scope: "team",
  },
  {
    code: "fitness_tech_obsolescence",
    expediteur: "Cardio Équipements Rousseau · Support logiciel",
    objet: "Fin de compatibilité de l'application de vos machines",
    corps:
      "L'application embarquée de votre génération d'appareils n'est plus compatible avec les téléphones récents. Nos autres clients constatent une hausse des réclamations et un surcoût de maintenance à chaque intervention.",
    signataire: "Le responsable du support",
    effet: "Disponibilité −10 % et coût matières +8 % pendant 2 tours (une entreprise tirée au sort)",
    enJeu: "Cycle de vie des actifs & veille technologique",
    nature: "internal",
    pli: "recommande",
    emoji: "⏳",
    scope: "team",
  },
  {
    code: "fitness_used_equipment_deal",
    expediteur: "Étude Marchand · Commissaire-priseur judiciaire",
    objet: "Vente du parc d'une salle en liquidation",
    corps:
      "Tapis de course, presses et vélos elliptiques, encore couverts par la garantie constructeur, sont proposés en lot unique. La mise à prix est très inférieure au neuf ; l'enlèvement doit intervenir sous quinzaine.",
    signataire: "Le commissaire-priseur",
    effet: "Disponibilité +12 % ce tour (équipe ciblée)",
    enJeu: "Décision d'investissement & coût d'opportunité",
    nature: "internal",
    pli: "simple",
    emoji: "🏭",
    scope: "team",
  },
  {
    code: "fitness_chaine_nationale",
    expediteur: "Syndicat des exploitants de salles de sport",
    objet: "Implantation d'un club premium d'enseigne nationale",
    corps:
      "Deux mille mètres carrés, piscine et espace bien-être ouvriront à trois kilomètres, pour vingt euros de plus par mois. Les clubs voisins constatent d'abord des visites de leurs adhérents réguliers, puis des résiliations.",
    signataire: "Le secrétaire du syndicat",
    effet: "Demande des pratiquants réguliers −15 % pendant 2 tours",
    enJeu: "Le concurrent premium ne prend que ceux qui en ont les moyens : reste à savoir s'il vous en laisse assez.",
    nature: "competition",
    pli: "simple",
    emoji: "🏊",
    scope: "market",
  },
  {
    code: "fitness_appli_gratuite",
    expediteur: "Observatoire des pratiques sportives",
    objet: "Note de tendance — essor des séances à domicile",
    corps:
      "Une application de séances guidées gratuites dépasse cinq millions d'utilisateurs. Notre enquête montre que les primo-pratiquants, ceux qui s'inscrivent en janvier, sont les premiers à préférer le domicile.",
    signataire: "Le directeur d'études",
    effet: "Demande des bonnes résolutions −20 % pendant 2 tours",
    enJeu: "Le concurrent le plus dangereux n'est pas toujours une salle : c'est celui qui remplace le besoin.",
    nature: "competition",
    pli: "simple",
    emoji: "📱",
    scope: "market",
  },
  {
    code: "fitness_mutuelle",
    expediteur: "Mutuelle régionale Prévoyance du Nord",
    objet: "Prise en charge de l'abonnement sportif de nos adhérents",
    corps:
      "Notre conseil d'administration a décidé de rembourser la moitié de l'abonnement en salle pour l'ensemble de nos adhérents. Votre club figure parmi les établissements référencés du département.",
    signataire: "Le directeur général",
    effet: "Demande des entreprises +30 % pendant 2 tours",
    enJeu: "Quand un tiers paie, le prix cesse d'être le frein : c'est la capacité d'accueil qui le devient.",
    nature: "market",
    pli: "recommande",
    emoji: "🩺",
    scope: "market",
  },
  {
    code: "fitness_coach_depart",
    expediteur: "Lettre de démission · Mme Fernandes, éducatrice sportive",
    objet: "Démission et rupture de mon contrat à l'issue du préavis",
    corps:
      "Je quitte le club pour rejoindre l'établissement situé en face, qui me propose des conditions supérieures. J'informerai mes groupes de cours de mon départ et de ma nouvelle affectation.",
    signataire: "Mme Fernandes",
    effet: "Demande de votre salle −10 % pendant 2 tours",
    enJeu:
      "Une salle qui dépend d'une personne dépend de ses choix : la fidélité doit aller à l'enseigne, pas au coach.",
    nature: "competition",
    pli: "recommande",
    emoji: "🏃",
    scope: "team",
  },
  {
    code: "fitness_portes_ouvertes",
    expediteur: "Note interne · Accueil du club",
    objet: "Bilan du week-end portes ouvertes",
    corps:
      "Deux cents visiteurs se sont présentés sur les deux jours, dont la moitié a effectué une séance d'essai complète. Une file s'est formée à l'accueil dès l'ouverture du lundi pour les inscriptions.",
    signataire: "La responsable d'accueil",
    effet: "Demande de votre salle +12 % ce tour",
    enJeu: "Un essai gratuit coûte une séance et rapporte un abonnement : c'est le coût d'acquisition le plus lisible.",
    nature: "market",
    pli: "simple",
    emoji: "🎟️",
    scope: "team",
  },
];
