import type { CourrierDef } from "../types";

/**
 * LA LIASSE DE NOVA — fabricant d'enceintes nomades.
 *
 * Ses correspondants récurrents : Électro-Composants Rhin pour les
 * composants, l'ébénisterie Vanhove pour les caissons, la Banque Régionale du
 * Nord, l'agence Berthaud pour la veille et la presse, le cabinet Vasseur pour
 * le droit des affaires. Les revoir d'un trimestre à l'autre fait un monde
 * plutôt qu'une suite d'aléas.
 */
export const NOVA_COURRIERS: CourrierDef[] = [
  {
    code: "raw_material_spike",
    expediteur: "Électro-Composants Rhin · Direction commerciale",
    objet: "Revalorisation de nos tarifs au 1er du trimestre",
    corps:
      "Les cours du cuivre et des terres rares ont progressé de plus de vingt pour cent depuis notre dernier barème. Nous ne pouvons plus absorber cette hausse et la répercutons sur l'ensemble de nos références, pour les deux prochains trimestres.",
    signataire: "Le directeur commercial",
    effet: "Coût des matières +20 % pendant 2 tours",
    enJeu: "Votre marge sur coût variable se comprime : où passe votre seuil de rentabilité ?",
    nature: "macro",
    pli: "email",
    emoji: "📈",
    scope: "market",
  },
  {
    code: "machine_breakdown",
    expediteur: "Note interne · Atelier d'assemblage",
    objet: "Arrêt de la ligne principale à la prise de poste",
    corps:
      "La ligne s'est arrêtée ce matin et n'est pas repartie. Le technicien évoque un défaut d'entretien sur le convoyeur ; la remise en route prendra plusieurs jours. Je vous transmets le constat pour décision.",
    signataire: "Le chef d'atelier",
    effet: "Disponibilité machine −15 % ce tour (une entreprise tirée au sort)",
    enJeu: "La maintenance était-elle à la hauteur ? La capacité est une ressource fragile.",
    nature: "internal",
    pli: "interne",
    emoji: "🔧",
    scope: "team",
  },
  {
    code: "viral_campaign",
    expediteur: "Agence Berthaud · Veille et relations presse",
    objet: "Forte exposition de vos enceintes sur les réseaux",
    corps:
      "Une vidéo tournée par un créateur suivi par plus d'un million de personnes met vos enceintes en scène. Les recherches sur votre marque ont doublé en quarante-huit heures. Vérifiez vos stocks sans attendre.",
    signataire: "Votre chargée de compte",
    effet: "Demande globale +8 % ce tour",
    enJeu: "Un pic de demande ne profite qu'à ceux qui ont du stock : anticipation !",
    nature: "market",
    pli: "simple",
    emoji: "🚀",
    scope: "market",
  },
  {
    code: "competitor_bankruptcy",
    expediteur: "Fédération de l'électronique grand public",
    objet: "Liquidation judiciaire de la société SONOR",
    corps:
      "Notre adhérent SONOR, présent depuis trente ans sur le marché des enceintes, a déposé son bilan. Ses cent quarante revendeurs cherchent dès à présent un fournisseur référencé. Nous tenons la liste à disposition de nos membres.",
    signataire: "Le délégué général",
    effet: "Demande globale +12 % pendant 2 tours",
    enJeu: "Une part de marché se prend au moment où elle se libère, pas après.",
    nature: "competition",
    pli: "simple",
    emoji: "🏳️",
    scope: "market",
  },
  {
    code: "economic_downturn",
    expediteur: "Observatoire régional de la consommation",
    objet: "Note de conjoncture — recul de la consommation des ménages",
    corps:
      "Le pouvoir d'achat recule pour le deuxième trimestre consécutif. Les achats d'équipement non indispensable sont les premiers reportés : notre panel enregistre une baisse de dix pour cent sur l'électronique de loisir.",
    signataire: "Le directeur d'études",
    effet: "Demande globale −10 % pendant 2 tours",
    enJeu: "Votre marge de sécurité absorbe-t-elle une baisse de 10 % des ventes ?",
    nature: "macro",
    pli: "simple",
    emoji: "🌧️",
    scope: "market",
  },
  {
    code: "student_fair",
    expediteur: "Salon de la Rentrée Étudiante · Commissariat général",
    objet: "Votre gamme au village high-tech du salon",
    corps:
      "Le salon ouvrira ses portes à quarante mille étudiants. Le village high-tech, où figurent vos enceintes nomades, sera l'un des trois pôles mis en avant dans la communication de l'événement.",
    signataire: "La commissaire générale",
    effet: "Demande du segment Étudiants +25 % ce tour",
    enJeu: "Un segment élastique au prix : la bonne offre au bon moment.",
    nature: "market",
    pli: "simple",
    emoji: "🎓",
    scope: "market",
  },
  {
    code: "premium_trend",
    expediteur: "Revue L'Écoute · Rédaction",
    objet: "Parution de notre dossier « le retour du son de studio »",
    corps:
      "Notre prochain numéro consacre douze pages au regain d'intérêt pour les enceintes haut de gamme, et vos modèles y figurent parmi les références citées. Nos lecteurs, exigeants et peu sensibles au prix, se déplacent chez les revendeurs dans les jours qui suivent la parution.",
    signataire: "Le rédacteur en chef",
    effet: "Demande du segment Passionnés +30 % ce tour",
    enJeu: "Le premium se gagne par la qualité perçue, pas par le prix seul.",
    nature: "market",
    pli: "simple",
    emoji: "💎",
    scope: "market",
  },
  {
    code: "rate_hike",
    expediteur: "Banque Régionale du Nord · Agence entreprises",
    objet: "Révision des conditions de vos concours bancaires",
    corps:
      "La banque centrale a relevé ses taux directeurs de soixante-quinze points de base. Conformément à l'article 4 de notre convention, le taux applicable à vos financements en cours est révisé à la hausse pour les deux prochains trimestres.",
    signataire: "Le directeur d'agence",
    effet: "Charges d'intérêts ×1,5 pendant 2 tours",
    enJeu: "L'effet de levier joue dans les deux sens : dette chère, rentabilité fragile.",
    nature: "macro",
    pli: "recommande",
    emoji: "🏦",
    scope: "market",
  },
  {
    code: "rate_cut",
    expediteur: "Banque Régionale du Nord · Agence entreprises",
    objet: "Baisse du taux applicable à vos financements",
    corps:
      "La détente monétaire engagée ce trimestre nous permet de réviser à la baisse le coût de vos concours. Nous restons à votre disposition pour étudier un financement complémentaire si vos projets d'investissement le justifient.",
    signataire: "Le directeur d'agence",
    effet: "Charges d'intérêts ×0,6 pendant 2 tours",
    enJeu: "Le bon moment pour financer par emprunt… si le projet crée de la valeur.",
    nature: "macro",
    pli: "simple",
    emoji: "🕊️",
    scope: "market",
  },
  {
    code: "supplier_discount",
    expediteur: "Électro-Composants Rhin · Direction commerciale",
    objet: "Offre de déstockage sur nos fins de série",
    corps:
      "Nos entrepôts doivent être libérés avant la fin du trimestre. Nous consentons pour cette seule période une remise exceptionnelle sur les composants concernés, dans la limite des quantités disponibles.",
    signataire: "Le directeur commercial",
    effet: "Coût des matières −10 % ce tour",
    enJeu: "Marge sur coût variable élargie : produire plus, ou marger plus ?",
    nature: "market",
    pli: "email",
    emoji: "📦",
    scope: "market",
  },
  {
    code: "supplier_dispute",
    expediteur: "Cabinet Vasseur · Avocats d'affaires",
    objet: "Litige contractuel avec votre fournisseur de composants",
    corps:
      "Votre fournisseur conteste les conditions de la commande passée au trimestre écoulé et suspend ses livraisons jusqu'au règlement du différend. En l'absence d'un second fournisseur référencé, l'approvisionnement de substitution se fera aux conditions du marché au comptant.",
    signataire: "Maître Vasseur",
    effet: "Coût des matières +15 % ce tour (une entreprise tirée au sort)",
    enJeu: "Dépendre d'un seul fournisseur est un risque qui se paie.",
    nature: "internal",
    pli: "recommande",
    emoji: "⚖️",
    scope: "team",
  },
  {
    code: "cold_wave",
    expediteur: "Préfecture · Cellule de crise départementale",
    objet: "Épisode de grand froid — restrictions de circulation",
    corps:
      "Un épisode de froid intense frappe la région pour plusieurs jours. La circulation des poids lourds est restreinte, les livraisons sont retardées et les ateliers non chauffés doivent réduire leur activité.",
    signataire: "Le directeur de cabinet",
    effet: "Disponibilité machine −10 % ce tour (tout le marché)",
    enJeu: "Quand tout le monde produit moins, qui a du stock vend.",
    nature: "macro",
    pli: "simple",
    emoji: "❄️",
    scope: "market",
  },
  {
    code: "team_overtime",
    expediteur: "Note interne · Délégation du personnel",
    objet: "Organisation exceptionnelle pour tenir les délais",
    corps:
      "Les équipes se sont entendues sur un roulement volontaire pour absorber le retard accumulé. Les heures supplémentaires sont acceptées et l'atelier tournera au-delà de sa cadence habituelle ce trimestre.",
    signataire: "Le délégué du personnel",
    effet: "Disponibilité machine +8 % ce tour (équipe ciblée)",
    enJeu: "La capacité n'est pas qu'une machine : c'est aussi un collectif.",
    nature: "internal",
    pli: "interne",
    emoji: "💪",
    scope: "team",
  },
  {
    code: "local_supplier_deal",
    expediteur: "Ébénisterie Vanhove · Gérance",
    objet: "Geste commercial sur vos caissons acoustiques",
    corps:
      "Nous travaillons ensemble depuis douze ans et vos volumes n'ont jamais faibli. Nous appliquons sur ce trimestre une remise sur l'ensemble de vos caissons, sans contrepartie et sans modification de nos délais.",
    signataire: "Le gérant",
    effet: "Coût des matières −8 % ce tour (équipe ciblée)",
    enJeu: "La relation fournisseur est un actif : elle élargit la marge sur coût variable.",
    nature: "internal",
    pli: "email",
    emoji: "🤝",
    scope: "team",
  },
  {
    code: "banker_goodwill",
    expediteur: "Banque Régionale du Nord · Agence entreprises",
    objet: "Révision de vos conditions à la suite de notre entretien",
    corps:
      "L'examen de vos derniers comptes et la trajectoire présentée lors de notre rendez-vous nous conduisent à revoir favorablement le taux de vos encours. Cette révision vaut pour les deux prochains trimestres et sera reconduite si la tendance se confirme.",
    signataire: "Votre chargé d'affaires",
    effet: "Charges d'intérêts ×0,7 pendant 2 tours (équipe ciblée)",
    enJeu: "La confiance bancaire se construit : elle se lit dans vos comptes.",
    nature: "internal",
    pli: "simple",
    emoji: "🏛️",
    scope: "team",
  },
  {
    code: "bank_penalties",
    expediteur: "Banque Régionale du Nord · Service des incidents de paiement",
    objet: "Mise en demeure — dépassements répétés de votre autorisation",
    corps:
      "Votre compte a présenté un solde débiteur non autorisé à cinq reprises ce trimestre. Nous vous mettons en demeure de régulariser ; dans l'intervalle, les commissions d'intervention et le taux majoré s'appliquent à l'ensemble de vos encours.",
    signataire: "Le responsable du service",
    effet: "Charges d'intérêts ×1,4 pendant 2 tours (équipe ciblée)",
    enJeu: "Une trésorerie mal pilotée coûte deux fois : le découvert, puis la sanction.",
    nature: "internal",
    pli: "recommande",
    emoji: "🧾",
    scope: "team",
  },
  {
    code: "export_market",
    expediteur: "NordSound Distribution · Direction des achats",
    objet: "Référencement de votre gamme dans notre réseau européen",
    corps:
      "Notre comité d'achats a retenu vos enceintes pour six cents points de vente en Belgique, aux Pays-Bas et en Allemagne. Le référencement prend effet immédiatement et porte sur les deux prochains trimestres.",
    signataire: "La directrice des achats",
    effet: "Demande globale +15 % pendant 2 tours",
    enJeu: "Un nouveau marché se sert avec de la capacité : qui peut produire plus, vendra plus.",
    nature: "market",
    pli: "simple",
    emoji: "✈️",
    scope: "market",
  },
  {
    code: "natural_disaster",
    expediteur: "Préfecture · Cellule de crise départementale",
    objet: "Reconnaissance de l'état de catastrophe naturelle",
    corps:
      "La tempête qui a traversé la zone industrielle a provoqué des inondations importantes. L'arrêté est publié : les entreprises assurées disposent de dix jours pour déclarer leur sinistre. Les autres supporteront seules leurs pertes d'exploitation.",
    signataire: "Le préfet",
    effet: "Disponibilité −28 % et matières +12 % ce tour, sauf pour les assurés",
    enJeu:
      "L'assurance échange un coût certain (la prime) contre un risque incertain : c'est un arbitrage d'espérance.",
    nature: "macro",
    pli: "recommande",
    emoji: "🌪️",
    scope: "market",
  },
  {
    code: "cyberattack",
    expediteur: "Axone Informatique · Cellule de sécurité",
    objet: "Incident de sécurité — chiffrement de votre gestion de production",
    corps:
      "Un rançongiciel a chiffré vos serveurs de production dans la nuit. Nous écartons toute négociation avec les attaquants et restaurons depuis les dernières sauvegardes. L'atelier fonctionnera en mode dégradé jusqu'au rétablissement.",
    signataire: "Le responsable de la sécurité",
    effet: "Disponibilité machine −12 % ce tour (équipe ciblée)",
    enJeu: "La continuité d'activité est un actif invisible, jusqu'au jour où elle manque.",
    nature: "internal",
    pli: "email",
    emoji: "💻",
    scope: "team",
  },
  {
    code: "tight_order",
    expediteur: "Centrale d'achat Priméo · Approvisionnements",
    objet: "Proposition de commande ferme — 500 unités",
    corps:
      "Nous vous proposons cinq cents unités au prix unitaire de cinquante-cinq euros, livrables sur le trimestre. Ce prix est ferme et non négociable ; la même proposition est faite à deux autres fabricants. Votre réponse nous est acquise sous huitaine.",
    signataire: "Le directeur des approvisionnements",
    effet: "+500 unités à 55 €/u imposés (échelle trimestre), dans la limite du stock",
    enJeu: "55 € couvre-t-il votre coût variable ? Les coûts pertinents décident, pas l'habitude.",
    nature: "market",
    pli: "recommande",
    emoji: "🏷️",
    scope: "team",
  },
  {
    code: "xxl_order",
    expediteur: "Plateforme Vendora · Direction des achats",
    objet: "Commande ferme de 2 500 unités pour notre opération de fin d'année",
    corps:
      "Notre opération de fin d'année portera sur deux mille cinq cents de vos enceintes, au prix unitaire de soixante et un euros. Nous savons votre atelier plus petit que ce volume : la sous-traitance est admise, à la condition que la qualité et les délais soient tenus. La commande ferme sera signée dès réception de votre accord.",
    signataire: "Le directeur des achats",
    effet: "+2 500 unités à 61 €/u (échelle trimestre), sous-traitance possible à 52 €/u",
    enJeu: "Sous-traiter à 52 pour vendre à 61, ou investir en capacité ? L'arbitrage make or buy en vrai.",
    nature: "market",
    pli: "recommande",
    emoji: "🏗️",
    scope: "team",
  },
  {
    code: "big_order",
    expediteur: "Groupe hôtelier Rivages · Direction des achats",
    objet: "Équipement de nos chambres — commande ferme de 600 unités",
    corps:
      "Nous équipons l'ensemble de nos chambres d'enceintes nomades et retenons votre modèle. La commande porte sur six cents unités, réglées comptant à la livraison, dans la limite de ce que vous pourrez livrer sur le trimestre.",
    signataire: "La directrice des achats",
    effet:
      "+600 unités (échelle trimestre) vendues d'office ce tour, réglées comptant, dans la limite du stock",
    enJeu:
      "Une opportunité ne se saisit qu'avec du stock ou de la capacité disponible : l'anticipation paie.",
    nature: "market",
    pli: "recommande",
    emoji: "📋",
    scope: "team",
  },
  {
    code: "major_breakdown",
    expediteur: "Maintenance Legrand · Service après-vente",
    objet: "Rapport d'intervention — avarie majeure sur votre chaîne",
    corps:
      "Le roulement principal a cédé et endommagé l'entraînement de la chaîne. La pièce est à fabriquer : comptez deux trimestres avant le retour à la cadence nominale. Notre rapport relève l'absence de graissage périodique depuis la mise en service.",
    signataire: "Le responsable technique",
    effet: "Disponibilité machine −30 % pendant 2 tours (une entreprise tirée au sort)",
    enJeu:
      "La maintenance préventive coûte. Ne pas la faire coûte bien plus — en capacité perdue et en ventes manquées.",
    nature: "internal",
    pli: "email",
    emoji: "🛑",
    scope: "team",
  },
  {
    code: "tech_obsolescence",
    expediteur: "Électro-Composants Rhin · Direction technique",
    objet: "Fin de commercialisation de la génération précédente",
    corps:
      "La nouvelle norme européenne rend obsolète la génération de composants sur laquelle vos machines sont réglées. Les pièces restantes sont facturées au tarif de fin de série et vos équipements perdront en rendement jusqu'à leur mise à niveau.",
    signataire: "Le directeur technique",
    effet: "Disponibilité −10 % et coût matières +8 % pendant 2 tours (une entreprise tirée au sort)",
    enJeu: "L'investissement ne sert pas qu'à produire plus : il sert aussi à ne pas produire moins.",
    nature: "internal",
    pli: "email",
    emoji: "⏳",
    scope: "team",
  },
  {
    code: "used_equipment_deal",
    expediteur: "Étude Marchand · Commissaire-priseur judiciaire",
    objet: "Vente aux enchères d'une ligne de montage — liquidation SONOR",
    corps:
      "Dans le cadre de la liquidation de la société SONOR, une ligne de montage de six ans, révisée, est mise en vente. La mise à prix représente le quart de sa valeur à neuf. La vente a lieu sous quinzaine, sur place et par voie électronique.",
    signataire: "Le commissaire-priseur",
    effet: "Disponibilité machine +12 % ce tour (équipe ciblée)",
    enJeu: "Racheter un actif d'occasion : un investissement rapide, mais quel effet sur la capacité réelle ?",
    nature: "internal",
    pli: "simple",
    emoji: "🏭",
    scope: "team",
  },
  {
    code: "nova_price_war",
    expediteur: "Agence Berthaud · Veille concurrentielle",
    objet: "Campagne de baisse de prix annoncée par SoundBox",
    corps:
      "SoundBox affiche moins quinze pour cent sur toute sa gamme, en vitrine, en ligne et sur quatre cents panneaux dans la région. Les comparateurs ont déjà répercuté les nouveaux prix, et vos revendeurs nous signalent des demandes d'alignement.",
    signataire: "Votre chargée de compte",
    effet: "Demande globale −12 % pendant 2 tours",
    enJeu:
      "S'aligner coûte de la marge, tenir coûte du volume : chiffrez les deux avant de choisir, ne suivez pas par réflexe.",
    nature: "competition",
    pli: "simple",
    emoji: "🥊",
    scope: "market",
  },
  {
    code: "nova_counterfeit",
    expediteur: "Cabinet Vasseur · Propriété industrielle",
    objet: "Contrefaçons de vos modèles sur les places de marché",
    corps:
      "Nous avons relevé près de deux mille annonces proposant des copies de vos enceintes à la moitié de votre prix. Les procédures de retrait sont engagées, mais elles prendront des semaines. Le public étudiant, très sensible au prix, ne distingue pas toujours la copie de l'original.",
    signataire: "Maître Vasseur",
    effet: "Demande des Étudiants −20 % ce tour",
    enJeu:
      "Un segment sensible au prix se détourne vite : ce que vaut votre marque se mesure au moment où on la copie.",
    nature: "competition",
    pli: "simple",
    emoji: "🏴‍☠️",
    scope: "market",
  },
  {
    code: "nova_campus_tender",
    expediteur: "CampusTech · Direction des achats",
    objet: "Appel d'offres — référencement audio de la rentrée",
    corps:
      "Notre enseigne renouvelle son rayon audio pour la rentrée et consulte quatre fabricants. Le marché porte sur l'ensemble de nos magasins. Nous rappelons que notre commission de référencement s'applique à chaque unité vendue.",
    signataire: "Le directeur des achats",
    effet: "Demande du canal CampusTech +30 % ce tour",
    enJeu: "Un canal partenaire prélève sa commission : le volume est là, la marge par unité, moins.",
    nature: "market",
    pli: "simple",
    emoji: "📑",
    scope: "market",
  },
  {
    code: "nova_engineer_leaves",
    expediteur: "Note interne · Service du personnel",
    objet: "Démission de votre ingénieur acoustique",
    corps:
      "Monsieur Leroy nous a remis sa démission ; il rejoint la société Auris à l'issue de son préavis. Les réglages d'accord et les essais d'écoute qu'il assurait seul devront être repris par l'atelier, avec le ralentissement que cela suppose.",
    signataire: "La responsable du personnel",
    effet: "Disponibilité machine −10 % pendant 2 tours",
    enJeu:
      "Une compétence clé est une capacité : quand elle part, l'atelier produit moins sans qu'aucune machine ne tombe.",
    nature: "internal",
    pli: "interne",
    emoji: "🚪",
    scope: "team",
  },
  {
    code: "nova_press_award",
    expediteur: "Revue L'Écoute · Rédaction",
    objet: "Attribution de notre Coup de cœur de l'année",
    corps:
      "Le jury de notre rédaction a distingué votre modèle parmi cent quatorze appareils testés cette année. La distinction paraîtra en couverture du numéro de rentrée ; nos lecteurs et les revendeurs indépendants y prêtent une attention réelle.",
    signataire: "Le rédacteur en chef",
    effet: "Demande de votre entreprise +10 % pendant 2 tours",
    enJeu:
      "La qualité perçue se paie d'avance et se récolte plus tard : c'est le rendement différé du budget qualité.",
    nature: "market",
    pli: "simple",
    emoji: "🏆",
    scope: "team",
  },
];
