import type { CourrierDef } from "../types";

/**
 * LA LIASSE DE ROUTE & CIE — transport routier régional.
 *
 * Le transport est réglementé, contrôlé et contractualisé : ses courriers
 * viennent des chargeurs, de la bourse de fret, de la gendarmerie, du garage
 * et du loueur. On y lit constamment la même tension — des camions immobilisés
 * d'un côté, des palettes qui attendent de l'autre.
 */
export const TRANSPORT_COURRIERS: CourrierDef[] = [
  {
    code: "transport_gazole",
    expediteur: "Centrale d'achat carburants Rouliers",
    objet: "Évolution de l'indice gazole applicable à vos enlèvements",
    corps:
      "L'indice de référence progresse de dix-huit pour cent en six semaines. Vos cartes carburant sont facturées au nouvel indice dès ce mois. La clause de révision de vos contrats de transport peut être activée sur justificatif.",
    signataire: "Le service adhérents",
    effet: "Coût du carburant +18 % pendant 2 tours",
    enJeu:
      "Une hausse du coût variable remonte mécaniquement le seuil : combien de palettes en plus faut-il charger ?",
    nature: "macro",
    pli: "email",
    emoji: "⛽",
    scope: "market",
  },
  {
    code: "transport_penurie_chauffeurs",
    expediteur: "Note interne · Exploitation",
    objet: "Deux démissions de conducteurs et annonces sans réponse",
    corps:
      "Deux de nos conducteurs rejoignent un concurrent qui propose une rémunération supérieure. Nos annonces sont sans réponse depuis cinq semaines. Deux véhicules resteront au dépôt faute de conducteur.",
    signataire: "Le responsable d'exploitation",
    effet: "Disponibilité de la flotte −14 % pendant 2 tours",
    enJeu: "Un camion sans chauffeur ne roule pas : la contrainte n'est pas toujours celle qu'on amortit.",
    nature: "market",
    pli: "interne",
    emoji: "🧑‍✈️",
    scope: "market",
  },
  {
    code: "transport_pic_ecommerce",
    expediteur: "Centrale logistique Nordis · Direction des transports",
    objet: "Appel à capacité pour le pic de fin d'année",
    corps:
      "Nos entrepôts passeront en trois-huit du quinze novembre au vingt-quatre décembre. Nous recherchons de la capacité auprès de l'ensemble de nos transporteurs référencés, aux conditions habituelles.",
    signataire: "Le directeur des transports",
    effet: "Demande de la distribution +35 % ce tour",
    enJeu: "Un pic ne se sert qu'avec une flotte disponible : la capacité se décide un trimestre à l'avance.",
    nature: "market",
    pli: "simple",
    emoji: "🎁",
    scope: "market",
  },
  {
    code: "transport_blocage_routier",
    expediteur: "Préfecture · Direction de la sécurité routière",
    objet: "Filtrage des accès à la métropole pendant quatre jours",
    corps:
      "Un mouvement de blocage filtre les accès à la métropole du lundi au jeudi. Aucune dérogation n'est prévue pour le transport de marchandises. Les itinéraires de contournement ajoutent en moyenne quatre-vingts kilomètres.",
    signataire: "Le directeur de cabinet",
    effet: "Disponibilité de la flotte −22 % ce tour",
    enJeu: "Le gazole a été brûlé, les chauffeurs payés, et rien n'a été livré : la perte est intégrale.",
    nature: "market",
    pli: "simple",
    emoji: "🚧",
    scope: "market",
  },
  {
    code: "transport_relocalisation",
    expediteur: "Agence de développement économique régionale",
    objet: "Implantation d'une unité de production sur le territoire",
    corps:
      "Un industriel rapatrie sa production dans la région et recherche un transporteur local pour ses flux entrants et sortants. Nous transmettons votre dossier ainsi que celui des autres opérateurs référencés.",
    signataire: "La directrice de l'agence",
    effet: "Demande des industriels +22 % pendant 2 tours",
    enJeu: "Un contrat régulier vaut mieux qu'un beau prix ponctuel : il remplit les camions tous les jours.",
    nature: "market",
    pli: "simple",
    emoji: "🏭",
    scope: "market",
  },
  {
    code: "transport_guerre_des_prix",
    expediteur: "Bourse de fret Cargolink · Note de marché",
    objet: "Effondrement des cotations sur les lots régionaux",
    corps:
      "L'arrivée d'opérateurs d'Europe de l'Est fait chuter les cotations sur l'ensemble des lots au départ de la région. Les prix relevés cette semaine sont inférieurs au coût de revient moyen de la profession.",
    signataire: "Le service études",
    effet: "Demande de l'affrètement −25 % pendant 2 tours",
    enJeu: "S'aligner sur un prix qui ne couvre pas la structure remplit les camions et vide la trésorerie.",
    nature: "competition",
    pli: "simple",
    emoji: "💸",
    scope: "market",
  },
  {
    code: "transport_credit_resserre",
    expediteur: "Loueur financier Trucklease · Direction des engagements",
    objet: "Révision des conditions de renouvellement de votre flotte",
    corps:
      "Les conditions applicables aux dossiers de financement de véhicules industriels sont durcies pour l'ensemble de notre portefeuille. Votre projet de renouvellement est concerné dès la prochaine échéance.",
    signataire: "Le directeur des engagements",
    effet: "Taux d'intérêt ×1,5 pendant 2 tours",
    enJeu: "Un métier qui immobilise un million en camions ressent chaque point de taux dans son résultat.",
    nature: "macro",
    pli: "recommande",
    emoji: "📉",
    scope: "market",
  },
  {
    code: "transport_accident",
    expediteur: "Assurances du Littoral · Service sinistres",
    objet: "Déclaration de sinistre — accident de circulation",
    corps:
      "Votre conducteur est indemne, le porteur est immobilisé et la marchandise transportée est endommagée. L'expertise est fixée à jeudi. La prise en charge des marchandises dépend de la garantie souscrite.",
    signataire: "Le gestionnaire de sinistres",
    effet: "Disponibilité −24 % et coût variable +12 % pendant 2 tours (une entreprise)",
    enJeu: "C'est ce que couvre l'assurance marchandise transportée : la prime se juge le jour du sinistre.",
    nature: "internal",
    pli: "simple",
    emoji: "🚨",
    scope: "team",
  },
  {
    code: "transport_panne_flotte",
    expediteur: "Garage Poirier Poids Lourds · Atelier",
    objet: "Immobilisation de trois porteurs — délai sur les pièces",
    corps:
      "Trois de vos porteurs sont entrés à l'atelier la même semaine, deux pour la transmission et un pour le circuit de freinage. Les pièces sont annoncées à quinze jours par le constructeur.",
    signataire: "Le chef d'atelier",
    effet: "Disponibilité de la flotte −28 % ce tour (une entreprise tirée au sort)",
    enJeu: "L'entretien différé coûte moins cher aujourd'hui et beaucoup plus cher le jour de la panne.",
    nature: "internal",
    pli: "email",
    emoji: "🔧",
    scope: "team",
  },
  {
    code: "transport_vol_remorque",
    expediteur: "Gendarmerie nationale · Brigade de recherches",
    objet: "Récépissé de dépôt de plainte — vol d'une remorque chargée",
    corps:
      "Votre plainte pour le vol d'une remorque et de son chargement sur votre parking a été enregistrée. Les images de vidéoprotection sont en cours d'exploitation. Ce récépissé vous est délivré pour vos démarches d'assurance.",
    signataire: "Le commandant de brigade",
    effet: "Disponibilité −20 % ce tour (une entreprise tirée au sort)",
    enJeu: "Le préjudice dépasse la remorque : c'est la confiance d'un client qui fait un tiers du trafic.",
    nature: "internal",
    pli: "simple",
    emoji: "🔒",
    scope: "team",
  },
  {
    code: "transport_label_qualite",
    expediteur: "Organisme certificateur Véritas Transport",
    objet: "Décision de certification — ponctualité des livraisons",
    corps:
      "Votre taux de livraisons dans le créneau annoncé dépasse le seuil requis sur quatre trimestres consécutifs. La certification vous est accordée et pourra être produite dans vos réponses aux appels d'offres industriels.",
    signataire: "Le responsable de la certification",
    effet: "Disponibilité commerciale +7 % pendant 2 tours (une entreprise)",
    enJeu: "Dans le transport, la ponctualité est le produit : elle se vend plus cher qu'un rabais ne rapporte.",
    nature: "market",
    pli: "simple",
    emoji: "🏅",
    scope: "team",
  },
  {
    code: "transport_banque_conciliante",
    expediteur: "Banque des Professions · Agence entreprises",
    objet: "Révision de vos conditions de découvert",
    corps:
      "Vos derniers comptes montrent un endettement contenu sous vos capitaux propres et des règlements clients qui rentrent dans les délais. Nous abaissons le coût de votre découvert pour les deux prochains trimestres.",
    signataire: "Votre chargée d'affaires",
    effet: "Taux d'intérêt ×0,7 pendant 2 tours (une entreprise)",
    enJeu:
      "La banque ne prête pas contre une promesse, elle lit vos comptes : c'est le rapport entre votre dette et vos capitaux propres qui décide de ce qu'elle consent.",
    nature: "macro",
    pli: "simple",
    emoji: "🤝",
    scope: "team",
  },
  {
    code: "transport_lot_surprise",
    expediteur: "Chargeur Delvigne · Service expéditions",
    objet: "Demande d'enlèvement en urgence pour demain matin",
    corps:
      "Notre transporteur habituel s'est décommandé en fin de journée. Neuf cents palettes doivent partir demain à six heures. Nous acceptons vos conditions tarifaires sous réserve d'une confirmation immédiate.",
    signataire: "Le responsable des expéditions",
    effet: "Commande ferme de 900 palettes ce tour (une entreprise tirée au sort)",
    enJeu:
      "Une commande ferme se sert sur la capacité restante : elle n'a de valeur que si les camions sont libres.",
    nature: "market",
    pli: "email",
    emoji: "📞",
    scope: "team",
  },
  {
    code: "transport_major_breakdown",
    expediteur: "Garage Poirier Poids Lourds · Atelier",
    objet: "Rapport d'expertise — casse moteur sur autoroute",
    corps:
      "Le moteur a cédé en pleine charge et l'expertise conclut à un défaut de suivi des vidanges. La réfection complète, moteur d'échange inclus, immobilisera le véhicule sur deux trimestres.",
    signataire: "Le chef d'atelier",
    effet: "Disponibilité −30 % pendant 2 tours (une entreprise tirée au sort)",
    enJeu: "Risque opérationnel & maintenance préventive",
    nature: "internal",
    pli: "email",
    emoji: "🛑",
    scope: "team",
  },
  {
    code: "transport_tech_obsolescence",
    expediteur: "Métropole · Service des zones à faibles émissions",
    objet: "Restriction d'accès pour les véhicules de votre catégorie",
    corps:
      "À compter du prochain trimestre, les véhicules de la catégorie de vos plus anciens porteurs ne sont plus autorisés dans le périmètre de la zone. Aucune dérogation professionnelle n'est prévue.",
    signataire: "Le chef de service",
    effet: "Disponibilité −10 % et coût matières +8 % pendant 2 tours (une entreprise tirée au sort)",
    enJeu: "Cycle de vie des actifs & veille technologique",
    nature: "internal",
    pli: "simple",
    emoji: "⏳",
    scope: "team",
  },
  {
    code: "transport_used_equipment_deal",
    expediteur: "Transports Cauchy · Cessation d'activité",
    objet: "Cession d'un porteur révisé, contrôle technique à jour",
    corps:
      "Nous cessons notre activité et cédons un porteur de quatre ans, entretenu en concession et contrôlé le mois dernier. Le prix demandé est nettement inférieur à la cote, l'enlèvement à votre charge.",
    signataire: "Le gérant",
    effet: "Disponibilité +12 % ce tour (équipe ciblée)",
    enJeu: "Décision d'investissement & coût d'opportunité",
    nature: "internal",
    pli: "simple",
    emoji: "🏭",
    scope: "team",
  },
  {
    code: "transport_concurrent_est",
    expediteur: "Bourse de fret Cargolink · Note de marché",
    objet: "Nouvel opérateur étranger sur les lots au départ de la région",
    corps:
      "Un transporteur immatriculé à l'étranger positionne quinze véhicules sur nos lots régionaux, à des tarifs inférieurs de vingt pour cent. Sur la bourse, l'attribution se fait au seul prix affiché.",
    signataire: "Le service études",
    effet: "Demande de l'affrètement −20 % pendant 2 tours",
    enJeu:
      "Sur la bourse, seul le prix compte : c'est le segment le plus exposé, et celui qu'on ne peut pas défendre par la qualité.",
    nature: "competition",
    pli: "simple",
    emoji: "🚛",
    scope: "market",
  },
  {
    code: "transport_distribution_internalise",
    expediteur: "Centrale logistique Nordis · Direction des transports",
    objet: "Internalisation progressive de nos flux régionaux",
    corps:
      "Notre groupe fait l'acquisition de sa propre flotte et recrute des conducteurs. Vos tournées régulières seront réduites à compter du prochain trimestre, puis réexaminées à l'échéance du contrat.",
    signataire: "Le directeur des transports",
    effet: "Demande de la grande distribution −15 % pendant 2 tours",
    enJeu:
      "Un client qui pèse un tiers du chiffre est un risque : le jour où il internalise, la flotte roule à vide.",
    nature: "competition",
    pli: "simple",
    emoji: "🏬",
    scope: "market",
  },
  {
    code: "transport_contrat_cadre",
    expediteur: "Aciéries Vandevelde · Direction des achats",
    objet: "Notification d'attribution — contrat-cadre de transport régional",
    corps:
      "À l'issue de la consultation, nous vous attribuons l'ensemble de nos flux régionaux pour une durée de deux ans, reconductible. Le volume prévisionnel et les engagements de service figurent en annexe.",
    signataire: "Le directeur des achats",
    effet: "Demande des industriels de votre entreprise +20 % pendant 2 tours",
    enJeu: "Un contrat-cadre lisse l'activité et sécurise la trésorerie : c'est ce qu'une banque aime lire.",
    nature: "market",
    pli: "recommande",
    emoji: "📜",
    scope: "team",
  },
  {
    code: "transport_controle_routier",
    expediteur: "Direction régionale des contrôles des transports terrestres",
    objet: "Procès-verbal — immobilisation de trois véhicules",
    corps:
      "Le contrôle a relevé une usure des pneumatiques inférieure au minimum légal sur trois de vos véhicules. Leur immobilisation est prononcée jusqu'à remise en état constatée par un professionnel agréé.",
    signataire: "Le contrôleur des transports terrestres",
    effet: "Disponibilité de la flotte −15 % ce tour",
    enJeu: "La maintenance qu'on n'a pas faite finit par se faire, au moment choisi par quelqu'un d'autre.",
    nature: "internal",
    pli: "recommande",
    emoji: "👮",
    scope: "team",
  },
  {
    code: "transport_peages",
    expediteur: "Société d'autoroutes du Nord · Service des abonnements",
    objet: "Revalorisation annuelle des tarifs de péage",
    corps:
      "Les tarifs applicables aux véhicules de classe 4 augmentent de six pour cent au premier janvier sur l'ensemble du réseau. Votre badge d'abonnement sera facturé au nouveau barème sans intervention de votre part.",
    signataire: "Le service des abonnements",
    effet: "Coût variable par tournée +6 % pendant 2 tours",
    enJeu:
      "Un coût variable qui monte se répercute sur le tarif, ou se paie sur la marge : la seule question est de savoir dans quel délai.",
    nature: "macro",
    pli: "simple",
    emoji: "🛣️",
    scope: "market",
  },
];
